name: Deploy site via Fleek
on:
  push:
    branches:
      - "release"
jobs:
  deploy-to-fleek:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [23]
    env:
      FLEEK_TOKEN: ${{ secrets.FLEEK_TOKEN }}
      FLEEK_PROJECT_ID: ${{ secrets.FLEEK_PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Install Fleek CLI
        run: pnpm add -g @fleek-platform/cli
      - name: Build & deploy sites
        run: fleek sites deploy
